newspaper/urls.py
from .views import *
from django.urls import path
urlpatterns = [
    path('', news_list, name='news_list_url'),
   	path('news/add/', NewsAdd.as_view(), name='news_add_url'),
    path('news/<str:id>/', news_detail, name='news_detail_url'),

]

web_django/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url("", include('newspaper.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newspaper/models.py
from django.db import models
from django.shortcuts import reverse

class News(models.Model):
	title = models.CharField(max_length=150, db_index=True)
	body = models.TextField(db_index=True)
	date_pub = models.DateTimeField(auto_now_add=True)
	def get_absolute_url(self):
		return reverse('news_detail_url', kwargs={'id':self.id})
	class Meta:
		ordering = ['-date_pub']


class Images(models.Model):
	id_news = models.ForeignKey('News', on_delete = models.CASCADE)
	pic = models.ImageField(upload_to='images/')

newspaper/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import *

class NewsForm(forms.ModelForm):
	images = forms 
	class Meta:
			model = News
			fields = ['title','body']
			widgets = {
			'title' : forms.TextInput(attrs={'class': 'form-control'}),
			'body' : forms.Textarea(attrs={'class': 'form-control'}),
			}


class ImagesForm(forms.ModelForm):
	class Meta:
		model = Images
		fields = ['pic']
		

#BookFormSet = inlineformset_factory(Author, Book, fields=('title',))
#author = Author.objects.get(name='Mike Royko')
#formset = BookFormSet(instance=author)

newspaper/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import View
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.db.models import Q
from django.forms.formsets import formset_factory

#quontity_news = 10

def news_list(request):
	quontity_news =1
	q_n = request.GET.get('rad', None)
	
	search_query = request.GET.get('search', '')
	if search_query:
		news = News.objects.filter(Q(title__icontains = search_query) | Q(body__icontains=search_query))
	else:
		news = News.objects.all()
		
	if 'quon_news' not in request.session:
		request.session['quon_news'] = 10

	if q_n is not None:
		request.session['quon_news'] = q_n
	paginator = Paginator(news,request.session['quon_news'])
	page_number = request.GET.get('page',1)
	page = paginator.get_page(page_number)
	is_paginated = page.has_other_pages()
	if page.has_previous():
		prev_url = '?page={}'.format(page.previous_page_number())
	else:
		prev_url = ''
	if page.has_next():
		next_url = '?page={}'.format(page.next_page_number())
	else:
		next_url = ''
	context = {
	'news': page,
	'is_paginated': is_paginated,
	'next_url': next_url,
	'prev_url': prev_url,
	}
	return render(request,'news/news_list.html', context = context)

def news_detail(request, id):
	n = News.objects.get(id__iexact=id)
	return render(request,'news/news.html',context = {'n':n})

class NewsAdd(View):
	def get(self,request):
		formNews = NewsForm()
		formImages = formset_factory(ImagesForm, extra=3,
												 min_num=1, validate_min=True)
		return render(request,'news/add_news.html', context = {'formNews':formNews,'formImages':formImages})
	def post(self, request):
		formImages = formset_factory(ImagesForm, extra=3,
												 min_num=1, validate_min=True)
		newsForm = NewsForm(request.POST)
	
		imgFormSet = formImages(request.POST or None, request.FILES or None)
		if len(request.FILES)!=0:
			if (newsForm.is_valid() and imgFormSet.is_valid()):
				news = newsForm.save()
				for inline_form in imgFormSet:
					if inline_form.cleaned_data:
						img = inline_form.save(commit=False)
						img.id_news = news
						img.save()
				return redirect(news_list)
		else:
			if newsForm.is_valid():
				news = newsForm.save()
				return redirect(news_list)
		return render(request,'news/add_news.html', context = {'formNews':newsForm,'formImages':imgFormSet})

newspaper/templates/news/add_news.html
{% extends 'news/base_news.html'%}
{% block title %}
Add news
{% endblock %}

{% block content %}
<form action="{% url 'news_add_url' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% for field in formNews %}
	<dir class="form-group">
		{% if field.errors %}
		<div class="alert alert-danger">
			{{field.errors }}
		</div>
		{% endif %}
	{{field.label}}
	{{field}}
	</dir>
	{% endfor %}

{% csrf_token %}

		{% for form in formImages %}
		{% for field  in form %}
		 
	<dir class="form-group">
		{% if field.errors %}
		<div class="alert alert-danger">
			{{field.errors }}
		</div>
		{% endif %}
	{{field.label}}
	{{field}}
	</dir>
	{% endfor %}
	{% endfor %}
	{{ formImages.management_form }}

	<button type="submit" class="btn btn-primary">Add</button>
	
</form>
{% endblock %}

newspaper/templates/news/base_news.html
{% extends 'base.html' %}



newspaper/templates/news/news.html
{% extends 'news/base_news.html'%}
{% block title %}
{{n.title}}
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{n.title }}</h5>
    <p class="card-text">{{n.body }}</p>
    <p class="card-text"><small class="text-muted">{{n.date_pub }}</small></p>
  </div>
  {% for img in n.images_set.all %}
  <img src="{{img.pic.url }}" class="card-img-bottom" alt="...">
  {% endfor %}
   
</div>
{% endblock %}

newspaper/templates/news/news_list.html
{% extends 'news/base_news.html'%}
{% block title %}
This is a news list
{% endblock %}

{% block r %}




{% endblock %}

{% block content %}

<script type="text/javascript">
function SetData (elem) { 
    localStorage.setItem(elem.getAttribute('name'), elem.getAttribute('id'));


} 
function GetData (item) { 
    return localStorage.getItem(item); 
}

window.onload = function() {
  
    var Item = GetData ('rad');
   
    if(Item != undefined) {
        document.getElementById(Item).checked = true;
    }

}

</script>

<form class="d-flex" action="{% url 'news_list_url' %}">
  <div class="form-check form-check-inline">
    <input class="form-check-input" type="radio" name="rad" id="inlineRadio1" value="10" onchange="SetData(this);">
    <label class="form-check-label" for="inlineRadio1">10</label>
  </div>
  <div class="form-check form-check-inline">
    <input class="form-check-input" type="radio" name="rad" id="inlineRadio2" value="20" onchange="SetData(this);">
    <label class="form-check-label" for="inlineRadio2">20</label>
  </div>
  <div class="form-check form-check-inline">
    <input class="form-check-input" type="radio" name="rad" id="inlineRadio3" value="50" onchange="SetData(this);">
    <label class="form-check-label" for="inlineRadio3">50</label>
  </div>
  <button class="btn btn-outline-success" type="submit">Applay</button>
</form>


	<h1 class="mb-5"> News:</h1>
	{% for n in news.object_list %}
	<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">{{n.title }}</h5>
    <p class="card-text">{{n.body|truncatewords:15 }}</p>
    <p class="card-text"><small class="text-muted">{{n.date_pub }}</small></p>
    <a href="{{ n.get_absolute_url }}" class="btn btn-primary">Read</a>
  </div>
  {% for img in n.images_set.all %}
  <img src="{{img.pic.url }}" class="card-img-bottom" alt="...">
  <br>
  {% endfor %}
</div>
	{% endfor %}

  {% if is_paginated %}
  <nav aria-label="...">
  <ul class="pagination">
    <li class="page-item {% if not prev_url %} disabled {% endif %}">
      <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">Previous</a>
    </li>

  
    
    {% for n in news.paginator.page_range %}
    {% if news.number == n %}
 <li class="page-item active" aria-current="page">
  <a class="page-link" href="?page={{n}}">{{n}}</a>
</li>
{% elif n > news.number|add:-3 and n < news.number|add:3 %}
<li class="page-item">
  <a class="page-link" href="?page={{n}}">{{n}}</a>
</li>
{% endif %}
    {% endfor %}
     <li class="page-item {% if not next_url %} disabled {% endif %}">
      <a class="page-link" href="{{ next_url }}" tabindex="-1" aria-disabled="true">Next</a>
    </li>
  </ul>
</nav>
{% endif %}
{% endblock %}






templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>
{% block title %}
title
{% endblock %}
	</title>

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'news_list_url' %}">Newspaper app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'news_add_url' %}">Add News</a>
        </li>
      
      
    </div>
  </div>
  <form class="d-flex" action="{% url 'news_list_url' %}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
   
</nav>
<div class="container">
<div class="row">
  <div class="col-6 offset-md-2">
  {% block content %}
text
{% endblock %}




  
  </div>
</div>
</div>

</body>
</html>